React & Redux group project - Space Travelers' Hub
Peter-Dumbari/Rocket-Group-Project- pull request #35
Opened 2023-06-30 14:05 UTC by Peter-Dumbari

## In this PR:
- We created a new repository and created `dev` branch which is the default branch 
- We have another branch called `development`  which serves as the development branch.
- we created other features branches and work according to the Kanban board, merging them at the end of the project
- We ran jest test 
- We ran linter validation 
- we created a pull request

2023-06-30 15:37 UTC, Abenezer-Tilahun requested changes
Hi @Peter-Dumbari  @gergitokusse   , 

Great job for implemented  the some of the Project Requirement , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No Linter errors
✔️ Correct Git -Flow
✔️ Good commit messages
✔️ Professional README

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 15:37 UTC, Abenezer-Tilahun commented on src/Test/Mission.test.js
> +});
- [ ] As stated in the project requirement Kindly make sure that to **add test for all your components and functions.**  and make sure that all of your test cases are pass but in the case of yours your test case for mission component is not passed Kindly Fix It.
![test case](https://github.com/Peter-Dumbari/Rocket-Group-Project-/assets/93598189/8cabb548-83d8-46b8-a86f-846db3b1bc3a)

2023-06-30 15:41 UTC, Peter-Dumbari commented on src/Test/Mission.test.js
> +});
@Abenezer-Tilahun, If I remove the `css` link, the test pass successfully
<img width="1280" alt="Screen Shot 2023-06-30 at 4 40 53 PM" src="https://github.com/Peter-Dumbari/Rocket-Group-Project-/assets/101636035/830564b5-f816-48ad-b7cf-c75e70c14b6c">

2023-06-30 16:34 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Team, 


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- Unit tests are running successfully :+1: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 16:34 UTC, FrederickMih commented on src/Test/Mission.test.js
> +});
- [ ] The two tests written are running successfully :+1: As requested by the previous reviewer, you'll be required to add more tests for the functionalities of your app. You wrote a single test to render the Mission component while you're equally required to write add more tests for more components and some pure functions in the redux store.

2023-06-30 18:12 UTC, OyePriscilla requested changes
Hi @Peter-Dumbari and @gergitokusse 👍, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Implemented test for `rocket `component 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 18:12 UTC, OyePriscilla commented on src/Test/Rocket.test.js
> +});
- [ ] Kudos for adding test as suggested earlier, 👍 can you please add tests for functions as well. ℹ️ This [link](https://redux.js.org/usage/writing-tests#unit-testing-individual-functions) might be of help. ℹ️ Kindly read through this header in particular **`Unit Testing Individual Functions.`**

2023-07-01 05:12 UTC, binhussen approved these changes
Hi @Peter-Dumbari and @gergitokusse , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Tested using Testing Library ✔️
- Well Structured Code ✔️
- Descriptive pull request ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 05:15 UTC, merged